#pragma once

#include <iostream>

static std::string DefaultConfigString = 
"# Download link:\n"
"# https://github.com/JekiTheMonkey/JKPS/releases \n"
"# My Discord: Jeki the Monkey from München#3932\n"
"# If any settings will not be found default parameter value will be used\n"
"#\n"
"# Read this page to know how to edit keys and mouse buttons from config\n"
"# https://gist.github.com/JekiTheMonkey/c40b346907ca0e3e8127f4fb0b5af1d5n \n"
"\n"
"[Keys]\n"
"Keys: Z,X\n"
"\n"
"[Mouse]\n"
"Buttons: No\n"
"\n"
"[Statistics text]\n"
"Statistics font: Default\n"
"Statistics text color: 255,255,255\n"
"Statistics character size: 13\n"
"Statistics bold: false\n"
"Statistics italic: false\n"
"Show statistics: true\n"
"Show max KPS on separate line: true\n"
"Show BPM: true\n"
"\n"
"[Buttons text]\n"
"Key counters font: Default\n"
"Key counters text color: 255,255,255\n"
"Key counters character size: 15\n"
"Key counters width: 1\n"
"Key counters height: 1.35\n"
"Key counters bold: false\n"
"Key counters italic: false\n"
"Only show set keys: false\n"
"Show key counters: true\n"
"\n"
"[Spacing]\n"
"# Distance from the borders and between the keys\n"
"Button distance: 6\n"
"# Distance between statistic lines\n"
"Statistics distance: 5\n"
"Space between buttons and statistics: 10\n"
"Space on the buttons right: 120\n"
"\n"
"[Button graphics]\n"
"Button texture: Default\n"
"Button texture size: 50,50\n"
"Button texture color: 30,30,30\n"
"\n"
"[Animation graphics]\n"
"Animation style: 1\n"
"Animation texture: Default\n"
"Animation velocity: 5\n"
"# Style 1\n"
"Animation scale on click: 1\n"
"Animation color: 255,180,0\n"
"# Style 2\n"
"Animation offset: 3\n"
"\n"
"[Background]\n"
"Background texture: Default\n"
"Background color: 170,170,170\n"
"\n"
"[Edit mode]\n"
"Edit mode alert color: 255,180,0\n"
"Highlighted text button color: 210,30,210\n"
"\n"
"[Theme developer]\n"
"# This is needed to test if key counters will fit in the window in a fast way\n"
"Value to multiply on click: 1\n";