#pragma once

#include <iostream>

static std::string DefaultConfigString = 
"# Download link:\n"
"# https://github.com/JekiTheMonkey/KPS/releases\n"
"# My Discord: Jeki the Monkey from München#3932\n"
"# If any settings will not be found default parameter value will be used\n"
"#\n"
"# Read this page to know how to edit keys and mouse buttons from config\n"
"# https://gist.github.com/JekiTheMonkey/c40b346907ca0e3e8127f4fb0b5af1d5n\n"
"\n"
"[Keys]\n"
"Keys: Z,X\n"
"\n"
"[Mouse]\n"
"Buttons: No\n"
"\n"
"[Statistics]\n"
"Statistics font: Default\n"
"Key counters font: Default\n"
"Statistics text color: 255,255,255\n"
"Key counters text color: 255,255,255\n"
"Statistics character size: 11\n"
"Key counters character size: 14\n"
"Show statistics: true\n"
"Show BPM: true\n"
"Only show set keys: false\n"
"Show key counters: true\n"
"\n"
"[Spacing]\n"
"# Distance from the borders and between the keys\n"
"Button distance: 7\n"
"Space between buttons and statistics: 10\n"
"Space on the statistics right: 35\n"
"\n"
"[Buttons Graphic]\n"
"Button texture: Default\n"
"Animation texture: Default\n"
"Button texture size: 50,50\n"
"Button texture color: 30,30,30\n"
"Animation velocity: 20\n"
"Animation scale on click: 1\n"
"Animation color: 255,180,0\n"
"\n"
"[Background]\n"
"Background texture: Default\n"
"Background color: 170,170,170\n"
"\n"
"[Other]\n"
"Changeability alert color: 255,0,0\n"
"Highlighted text button color: 255,0,0\n";