#pragma once

#include <iostream>

static std::string DefaultConfigString = 
"# This config file contains all KPS settings\n"
"#\n"
"# If executable file of KPS will not find any config in its directory\n"
"# it will generate one by itself\n"
"#\n"
"# If anything will not be found it will be replaced by default settings\n"
"#\n"
"# Single keys MUST be written in Caps\n"
"# Available keys to set you can get there\n"
"# https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Keyboard.php\n"
"# UpArrow, DownArrow etc can be written like so\n"
"\n"
"[Keys]\n"
"Keys: Z,X\n"
"\n"
"Statistics font: Ubuntu-Regular.ttf\n"
"Key counters font: Ubuntu-Regular.ttf\n"
"Statistics text color: 255,255,255\n"
"Key counters text color: 0,0,0\n"
"Statistics character size: 12\n"
"Key counters character size: 22\n"
"Show statistics: true\n"
"Show key counters: true\n"
"\n"
"[Spacing]\n"
"# Distance from the borders and between the keys\n"
"Distance: 7\n"
"Space between buttons and statistics: 10\n"
"\n"
"[Buttons Graphic]\n"
"Button image: ButtonTexture.png\n"
"Button texture size: 50,50\n"
"Button image color: 255,255,255,255\n"
"Animation velocity: 20\n"
"Animation color: 255,255,255,255\n"
"\n"
"[Background]\n"
"Background texture: BackgroundTexture.png\n"
"Background color: 44,28,31,180\n"
"\n"
"[Other]\n"
"Changeability alert color: 255,0,0\n";