#pragma once

#include <string>


static const std::string defCfgComment = 
R"(# Download link:
# https://github.com/JekiTheMonkey/JKPS/releases 
# My Discord: Jeki the Monkey from München#3932
# If any settings will not be found default parameter value will be used
#
# Everything about config:
# https://gist.github.com/JekiTheMonkey/06c7b7dc0401729c2574a04442b19225
)";

// static const std::string defCfg =  defCfgComment +
// "\n"
// "[Keys]\n"
// "Keys: Z,X\n"
// "Visual keys: Z,X\n"
// "\n"
// "[Mouse]\n"
// "Buttons: No\n"
// "Visual buttons: No\n"
// "\n"
// "[Statistics text]\n"
// "Statistics text distance: 5\n"
// "Space between buttons and statistics: 15\n"
// "Statistics text font: Default\n"
// "Statistics text color: 255,255,255\n"
// "Statistics text character size: 14\n"
// "Statistics text bold: False\n"
// "Statistics text italic: False\n"
// "Show statistics text: True\n"
// "Show KPS: True\n"
// "Show max KPS on separate line: True\n"
// "Show total: True\n"
// "Show BPM: True\n"
// "\n"
// "[Buttons text]\n"
// "Buttons text font: Default\n"
// "Buttons text color: 255,255,255\n"
// "Buttons text character size: 15\n"
// "Buttons text width: 0\n"
// "Buttons text height: 0\n"
// "Buttons text horizontal bounds: 4\n"
// "Buttons text vertical bounds: 4\n"
// "Buttons text bold: False\n"
// "Buttons text italic: False\n"
// "Only show set keys: False\n"
// "Show key counters: True\n"
// "\n"
// "[Button graphics]\n"
// "Button distance: 6\n"
// "Button texture: Default\n"
// "Button texture size: 60,60\n"
// "Button texture color: 30,30,30\n"
// "\n"
// "[Animation graphics]\n"
// "Animation style: 1\n"
// "Animation texture: Default\n"
// "Animation velocity: 5\n"
// "# Style 1\n"
// "Animation scale on click: 1\n"
// "Animation color: 255,180,0\n"
// "# Style 2\n"
// "Animation offset: 3\n"
// "\n"
// "[Background]\n"
// "Background texture: Default\n"
// "Background color: 170,170,170\n"
// "Scale background texture if it does not fit: True\n"
// "\n"
// "[Main window]\n"
// "Window title bar: False\n"
// "Window bonus size top: 6\n"
// "Window bonus size bottom: 6\n"
// "Window bonus size left: 6\n"
// "Window bonus size right: 130\n"
// "\n"
// "[KPS window]\n"
// "Enable from start: false\n"
// "Window size: 300,300\n"
// "KPS Background color: 0,177,64\n"
// "Text font: Default\n"
// "Text size: 130\n"
// "Number size: 100\n"
// "KPS extra window distance from top: 20\n"
// "KPS extra window distance between text: 50\n"
// "\n"
// "[Theme developer]\n"
// "Value to multiply on click: 1\n";